ARG BASE_TAG=x64

FROM forumi0721/alpine-base:${BASE_TAG} as builder_stage1

LABEL maintainer="forumi0721@gmail.com"

ARG BUILD_TAG=aarch64

COPY local/bin/docker-build-stage1 /usr/local/bin/

RUN ["docker-build-stage1"]



#FROM forumi0721/scratch:aarch64 as builder_yay
#
#LABEL maintainer="forumi0721@gmail.com"
#
#ARG BUILD_TAG=aarch64
#
#COPY --from=builder_stage1 /output /
#
#COPY local/bin/docker-build-yay /usr/local/bin/
#
#RUN ["docker-build-yay"]



FROM forumi0721/scratch:aarch64 as builder_stage2

LABEL maintainer="forumi0721@gmail.com"

ARG BUILD_TAG=aarch64

COPY --from=builder_stage1 /output /

#COPY --from=builder_yay /output /output

COPY local/bin/docker-build-stage2 /usr/local/bin/

RUN ["docker-build-stage2"]



FROM forumi0721/scratch:aarch64

LABEL maintainer="forumi0721@gmail.com"

COPY --from=builder_stage2 / /

ENTRYPOINT ["docker-run"]

