ARG BASE_TAG=x64

FROM forumi0721/alpine-base:${BASE_TAG} as builder_stage1

LABEL maintainer="forumi0721@gmail.com"

ARG BUILD_TAG=armv7

COPY local/bin/docker-build-stage1 /usr/local/bin/

RUN ["docker-build-stage1"]



FROM forumi0721/scratch:armv7 as builder_yaourt

LABEL maintainer="forumi0721@gmail.com"

ARG BUILD_TAG=armv7

COPY --from=builder_stage1 /output /

COPY local/bin/docker-build-yaourt /usr/local/bin/

RUN ["docker-build-yaourt"]



FROM forumi0721/scratch:armv7 as builder_stage2

LABEL maintainer="forumi0721@gmail.com"

ARG BUILD_TAG=armv7

COPY --from=builder_stage1 /output /

COPY --from=builder_yaourt /output /output

COPY local/bin/docker-build-stage2 /usr/local/bin/

RUN ["docker-build-stage2"]



FROM forumi0721/scratch:armv7

LABEL maintainer="forumi0721@gmail.com"

COPY --from=builder_stage2 / /

ENTRYPOINT ["docker-run"]

