ARG BUILD_TAG=latest

FROM forumi0721/alpine-base:${BUILD_TAG} as stage1

LABEL maintainer="forumi0721@gmail.com"

ENV TARGET_ARCH=aarch64

COPY local/. /usr/local/

RUN ["docker-init"]



FROM forumi0721/arch-base:${BUILD_TAG} as yaourt

LABEL maintainer="forumi0721@gmail.com"

COPY local/. /usr/local/

#RUN ["docker-build-start"]

RUN ["docker-build"]

#RUN ["docker-build-end"]



FROM scratch as stage2

LABEL maintainer="forumi0721@gmail.com"

COPY --from=stage1 /build/archroot /

COPY --from=yaourt /output /output

COPY local/. /usr/local/

RUN ["docker-build-start"]

RUN ["docker-init"]

RUN ["docker-build-end"]



FROM scratch

LABEL maintainer="forumi0721@gmail.com"

COPY --from=stage2 / /

RUN ["docker-build-start"]

RUN ["docker-init"]

RUN ["docker-build-end"]

ENTRYPOINT ["docker-run"]

