ARG BUILD_ARCH=x64

FROM forumi0721debian${BUILD_ARCH}build/debian-${BUILD_ARCH}-qemu-static-builder:latest as qemu

FROM forumi0721/alpine-${BUILD_ARCH}-base:latest as stage1

LABEL maintainer="forumi0721@gmail.com"

ENV TARGET_ARCH=aarch64

COPY local/. /usr/local/

COPY --from=qemu /output/qemu-static /usr/local/bin

RUN ["docker-init"]



FROM scratch as stage2

LABEL maintainer="forumi0721@gmail.com"

COPY --from=stage1 /build/archroot /

COPY local/. /usr/local/

RUN ["docker-build-start"]

RUN ["docker-init"]

RUN ["docker-build-end"]



FROM scratch

LABEL maintainer="forumi0721@gmail.com"

COPY --from=stage2 / /

RUN ["docker-build-start"]

RUN ["docker-init"]

RUN ["docker-build-end"]

ENTRYPOINT ["docker-run"]

