ARG BUILD_ARCH=armhf

FROM forumi0721/alpine-${BUILD_ARCH}-base:latest as stage1

LABEL maintainer="forumi0721@gmail.com"

ENV TARGET_ARCH=armhf

COPY local/. /usr/local/

RUN ["docker-init"]



FROM scratch as stage2

COPY --from=stage1 /build/archroot /

COPY local/. /usr/local/

RUN ["docker-build-start"]

RUN ["docker-init"]

RUN ["docker-build-end"]



FROM scratch

COPY --from=stage2 / /

ENTRYPOINT ["docker-run"]

